# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XkR5fJjNTJkPTp4XMxvuWKkuBxXiNcz2
"""

A=int(input())
A=A**3
if A>50:
  print("Massive Number")
else:
  print("Small Number")  
print("Code is complete!")

User=input("Enter your password-")
Password_2=input("Enter your password-")
if User==Password_2:
  print("Passwords matched!")
else:
  print("Passwords mismatch. Check again")

x=int(input())
if x%200==0 or x%500==0:
  print("Dispatching Cash!") 
else:
  print("Denomination not available!")

time=int(input())

if time >= 9 and time < 12:
    print("Good Morning")
else:
    if time >= 12 and time < 17:
        print("Good Afternoon")
    else:
        if time >= 17 and time < 24:
            print("Good Night")
        else:
            print("SOJAAOO!")

time=int(input())
if time >= 9 and time < 12:
    print("Good Morning")
elif time >= 12 and time < 17:
    print("Good Afternoon")
elif time >= 17 and time < 24:
    print("Good Night")
else:
    print("SOJAAOO!")

x=int(input())
if x<0:
  print("x is negative")
else:
  print("x is positive")

x=int(input())
if x>0:
  print("x is positive") 
else:
  if x==0:
    print("Zero")
  else:
    print("x is negative")

x=int(input())

if 0<x<=9:
  if (x**5%50+20-6)>15:
    print("Black")
  else:
    print("Blue")  
else:
  print("Number not valid!")

x=int(input())

if not(0<x<=9):
  print("Number not valid!")
elif (x**5%50+20-6)>15:
    print("Black")
else:
    print("Blue")

my_choice=input("Enter your language-")
if my_choice=="Python":
  print("Great choice!")
else:
  print("Think once again")

feedback=input()
if feedback:
  print("Thank you for giving feedback")
else:
  print("Please provide feedback next time")

feedback=input()
if not feedback:
  print("Please provide feedback next time")
else:
  print("Thank you for giving feedback")

feedback=input()
if feedback=="":
  print("Please provide feedback next time")
else:
  if feedback=="Super" or feedback=="Good" or feedback=="Great":
    print("Thank you so much")
  else:
    print("Thank you for giving feedback")

#FIZZBUZZ
# 1. Take an integer input n.
# 2. If N is a multiple of 3 -> print FIZZ
# 3. If N is a multiple of 5 -> print BUZZ
# 4. If N is a multiple of both 3 and 5 -> print FIZZBUZZ
# Otherwise print nothing.

n=int(input())
if n%3==0 and n%5==0:
  print("FIZZBUZZ") 
elif n%3==0:
  print("FIZZ")
elif n%5==0:
  print("BUZZ")
else:
  print("Invalid!")

a = 50
if a > 40:
    print("A")
if a > 30:
    print("B")
if a > 20:
    print("C")

# Take in three inputs from a user which are marksin english, maths and science.
# Assign streams according to the following criteria.
# if science > 90 or marks in all are greater than 75 -> Science
# if marks in all are greater than 60 and less than 75 -> Commerce
# if marks in any are less than 60 -> Humanities

English=int(input("Marks in English:"))
Maths=int(input("Marks in Maths:"))
Science=int(input("Marks in Science:"))
if Science>90 or English>75 and Maths>75 and Science>75:
  print("Science")
elif 60<English<75  and 60<Maths<75 and 60<Science<75:
  print("Commerce")
elif English<60 or Maths<60 or Science<60:
  print("Humanities")

# Build a meter system for an auto. Take into two inputs. 
# Kilometers Travelled and Stall Time (in minutes). Rate List -
# First 10 kms - Rs 10 per Km
# Next 40 kms - Rs 9 per Km
# Next 100 kms - Rs 8 per Km
# Any leftover km count - Rs. 6 per Km
# Rs 5 extra for every minute of Stall Time.

D=int(input("Distance Travelled (in KM):"))
T=int(input("Stall Time (in Min):"))
if 0<D<=10:
  print((D*10)+(T*5))
elif 10<D<=50:
  print(100+((D-10)*9)+(T*5))
elif 50<D<=150:
  print(460+((D-50)*8)+(T*5)) 
elif D>150:
  print(1260+((D-150)*6)+(T*5))

# Generate electricity bill using the following rate card.
# Take units consumed as input -
# If < 100 units -> Free
# If >= 100 units and < 200 units -> Rs 2 per unit
# If >= 200 units -> Rs 5 per unit

U=int(input("Units Consumed:"))
if U<100:
  print("Free")
elif 100<=U<200:
  print((U-99)*2)
elif U>=200:
  print(200+(U-199)*5)

N=int(input())
M=int(input())
10<=N<=20
if not(10<=N<=20):
  print("-1")
elif 10<=N<=20:
  print(N+M)
  if (N+M)>=100:
    print("That is a large sum!")

A=int(input())
if A%400==0:
  print(1)
elif A%4==0 and A%100!=0:
    print(1)
else:
    print(0)

if False:
  print("M")
elif True:
  print("D")
elif True:
  print("A")
else:
  print("K")

a=int(input())
b=int(input())
c=int(input())

if (a==b or a==c) or b==c:
  print("equilateral")
elif a==b and b==c or c==a:
  print("isosceles")
else:
  print('scalene')